################################################################################
#
#    Licensed to the Apache Software Foundation (ASF) under one or more
#    contributor license agreements.  See the NOTICE file distributed with
#    this work for additional information regarding copyright ownership.
#    The ASF licenses this file to You under the Apache License, Version 2.0
#    (the "License"); you may not use this file except in compliance with
#    the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
################################################################################

#
# All the values specified here will override the default values given
# in config.properties.
#

karaf.systemBundlesStartLevel=50

#
# You can place any customized configuration here.
#

org.osgi.framework.system.packages.extra= \
 com.databricks.spark.avro.*;version="3.2.0", \
 org.apache.spark.*, \
 org.apache.kafka.*, \
 com.amazonaws.services.kinesis.*, \
 org.eclipse.paho.client.mqttv3.*;version="1.2.0", \
 org.apache.bahir.*, \
 org.apache.hadoop.security.*, \
 org.apache.hadoop.conf.*, \
 org.apache.hadoop.mapred.*, \
 org.apache.hadoop.mapreduce.*, \
 org.apache.hadoop.hdfs.*, \
 org.apache.hadoop.util.*, \
 org.apache.hadoop.io.*, \
 org.apache.hadoop.fs.*, \
 org.apache.parquet.*, \
 scala.*;version="2.13.6", \
 com.pentaho.commons.dsc, \
 com.pentaho.commons.dsc, \
 com.pentaho.commons.dsc.params, \
 com.pentaho.commons.dsc.tlsup.*, \
 com.pentaho.commons.dsc.api, \
 com.pentaho.commons.dsc.api.params, \
 com.pentaho.commons.dsc.api.tlsup.*, \
 com.pentaho.commons.dsc.api.tlsup.util, \
 com.pentaho.commons.dsc.validator, \
 com.pentaho.commons.dsc.validator.params, \
 com.pentaho.commons.dsc.validator.tlsup.*, \
 com.pentaho.commons.dsc.*, \
 com.pentaho.messages.*, \
 org.pentaho.commons.util.*, \
 org.pentaho.di.webspoon.*, \
 com.pentaho.big.data.bundles.impl.shim.*, \
 org.pentaho.big.data.impl.shim.*, \
 org.pentaho.hadoop.shim.*;version="10.2", \
 org.pentaho.hadoop.mapreduce.*, \
 org.pentaho.hbase.shim.common.*, \
 org.apache.oozie.client.*, \
 org.apache.pig.*, \
 com.sun.security.auth.module, \
 sun.misc, \
 com.tinkerpop.blueprints.*, \
 mondrian.olap4j.*, \
 mondrian.spi.*, \
 mondrian.xmla.*, \
 org.osjava.sj.*, \
 org.safehaus.uuid, \
 javax.annotation.*;version="1.2", \
 javax.xml.soap, \
 javax.xml.rpc.*, \
 javax.xml.bind.*;version="2.3.3", \
 org.jfree.*, \
 org.pentaho.reporting.libraries.*, \
 org.apache.commons.collections.*, \
 org.apache.commons.logging.*; version="1.2", \
 org.apache.commons.configuration.*; version="1.9", \
 org.apache.commons.dbcp, \
 org.apache.http; version="4.4.11", \
 org.apache.http.annotation; version="4.4.11", \
 org.apache.http.concurrent; version="4.4.11", \
 org.apache.http.config; version="4.4.11", \
 org.apache.http.entity; version="4.4.11", \
 org.apache.http.impl; version="4.4.11", \
 org.apache.http.impl.bootstrap; version="4.4.11", \
 org.apache.http.impl.entity; version="4.4.11", \
 org.apache.http.io; version="4.4.11", \
 org.apache.http.pool; version="4.4.11", \
 org.apache.http.message; version="4.4.11", \
 org.apache.http.params; version="4.4.11", \
 org.apache.http.pool; version="4.4.11", \
 org.apache.http.protocol; version="4.4.11", \
 org.apache.http.ssl; version="4.4.11", \
 org.apache.http.util; version="4.4.11", \
 org.apache.http.auth.*; version="4.5.14", \
 org.apache.http.client.*; version="4.5.14", \
 org.apache.http.conn.*; version="4.5.14", \
 org.apache.http.cookie.*; version="4.5.14", \
 org.apache.http.impl.auth; version="4.5.14", \
 org.apache.http.impl.client; version="4.5.14", \
 org.apache.http.impl.conn; version="4.5.14", \
 org.apache.http.impl.conn.tsccm; version="4.5.14", \
 org.apache.http.impl.cookie; version="4.5.14", \
 org.apache.http.impl.execchain; version="4.5.14", \
 org.apache.commons.math, \
 org.apache.commons.math.distribution, \
 org.apache.commons.pool, \
 org.apache.commons.pool.impl, \
 org.apache.commons.vfs, \
 org.apache.commons.vfs.provider.http, \
 org.apache.commons.vfs2.*; version="2.10.0", \
 org.apache.commons.lang3.*; version="3.14.0", \
 org.apache.html.dom; version="2.11.0", \
 org.apache.karaf.branding, \
 org.apache.karaf.service.guard.tools; version="4.4.6", \
 org.apache.karaf.util.maven; version="4.4.6", \
 org.apache.log4j; version="2.24.1", \
 org.apache.log4j.*; version="2.24.1", \
 org.apache.logging.log4j; version="2.24.1", \
 org.apache.logging.log4j.*; version="2.24.1", \
 org.apache.wml.dom; version="2.11.0", \
 org.apache.wml; version="2.11.0", \
 org.apache.xerces.*; version="2.12.2", \
 org.apache.xml.serialize; version="2.11.0", \
 org.apache.xpath.domapi, \
 org.codehaus.enunciate.*, \
 org.eclipse.jface.dialogs, \
 org.eclipse.jface.wizard, \
 org.eclipse.jface.viewers, \
 org.eclipse.jface.window, \
 org.eclipse.swt.*, \
 org.eclipse.rap.rwt.*; version\="3.12.0", \
 org.olap4j.*, \
 org.pentaho.capabilities.*; version="10.2.0.9-408", \
 org.pentaho.di.*, \
 org.pentaho.dictionary, \
 org.pentaho.metastore.*, \
 org.pentaho.kettle.repository.locator.api, \
 org.pentaho.metastore.locator.api, \
 org.eigenbase.xom.*, \
 org.pentaho.metaverse.api.*, \
 org.pentaho.osgi.api;version="10.2.0.9-408", \
 org.pentaho.platform.proxy.*;version="10.2.0.9-408", \
 org.pentaho.platform.api.monitoring.snmp;version="10.2.0.9-408", \
 org.pentaho.ui.xul.*, \
 org.pentaho.vfs.ui, \
 org.pentaho.xul.swt.tab, \
 org.pentaho.platform.*, \
 org.slf4j.*; version="2.0.12", \
  org.slf4j.*; version="1.7.0", \
 org.springframework.dao; version="5.3.39", \
 org.springframework.security.*; version="5.8.16", \
 org.springframework.beans.*; version="5.3.39", \
 org.springframework.context.*; version="5.3.39", \
 org.springframework.core.io; version="5.3.39", \
 org.springframework.util; version="5.3.39", \
 org.springframework.web.*; version="5.3.39", \
 org.yaml.snakeyaml; version="2.2", \
 org.yaml.snakeyaml.*; version="2.2", \
 org.pentaho.database, \
 org.pentaho.database.*, \
 com.thoughtworks.xstream;version="1.4.20", \
 com.thoughtworks.xstream.*;version="1.4.20", \
 com.sun.jersey.api.client;version="1.19.1", \
 com.sun.jersey.api.client.*;version="1.19.1", \
 com.sun.jersey.core.header;version="1.19.1", \
 com.sun.jersey.multipart;version="1.19.1", \
 javax.ws.rs.core;version="1.1.1", \
 javax.ws.rs.ext;version="1.1.1", \
 org.dom4j.*;version="2.1.4", \
 org.dom4j;version="2.1.4", \
 org.pentaho.metadata.*, \
 org.pentaho.pms.core.*, \
 org.pentaho.pms.schema.*, \
 org.pentaho.platform.servicecoordination.api;version="10.2.0.9-408", \
 org.pentaho.platform.servicecoordination.impl;version="10.2.0.9-408", \
 org.json.simple;version="1.1.0", \
 mondrian.*, \
 olap4j.*, \
 org.owasp.encoder.*, \
 io.reactivex.*;version="2.2.3", \
 org.pentaho.di.engine.*;version="10.2.0.9-408", \
 org.pentaho.di.engine.spark.*;version="10.2.0.9-408", \
 org.reactivestreams.*;version="1.0.0", \
 org.apache.hadoop.hbase.*, \
 org.apache.hadoop.hbase.client.*, \
 org.apache.hadoop.hbase.io.*, \
 org.apache.hadoop.hbase.mapreduce.*, \
 org.apache.hadoop.hbase.mapred.*, \
 org.apache.hbase.thirdparty.*, \
 org.apache.hbase.thirdparty.com.google.common.primitives.*, \
 org.apache.hadoop.hbase.protobuf.*, \
 org.apache.hadoop.hbase.protobuf.generated.*, \
 org.apache.hadoop.hbase.util.*,\
 com.google.common.collect;version="12.0.0", \
 com.cloudera.impala.*, \
 com.cloudera.impala.jdbc41.*, \
 org.apache.calcite.sql.*, \
 org.apache.hadoop.hive.ql.*, \
 com.hortonworks.hwc.*, \
 com.hortonworks.spark.sql.hive.llap.*, \
 org.mysql.jdbc.*, \
 com.mysql.jdbc.*, \
 org.gjt.mm.mysql.*, \
 org.h2.*, \
 com.cloudera.impala.jdbc41, \
 org.postgresql.*, \
 org.pentaho.di.trans.steps.mongodb.*;version="10.2.0.9-408", \
 org.pentaho.di.trans.steps.mongodbinput.*;version="10.2.0.9-408", \
 org.pentaho.di.trans.steps.mongodboutput.*;version="10.2.0.9-408", \
 org.pentaho.mongo.wrapper.field.*;version="10.2.0.9-408", \
 com.mongodb.*;version="3.12.10", \
 com.mongodb.util.*;version="3.12.10", \
 org.pentaho.di.core.namedcluster.*;version="10.2.0.9-408",\
 org.apache.commons.collections4.map.*;version="4.4",\
 org.ops4j.pax.swissbox.core.*;version="1.8.2"

karaf.shutdown.port=-1
org.osgi.framework.storage.clean=none
